version: '3.5'
    
volumes:
  prometheus-data:
    driver: local
  grafana-data:
    driver: local
  jaeger-data:
    driver: local
  elasticsearch-data:
    driver: local
  loggingdb:
    driver: local
  mysql_workbench:
    driver: local

services:
  catalogdb:
    container_name: catalogdb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
        
  reportinggatewaydb:
    container_name: reportinggatewaydb
    restart: always
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db

  basketdb:
    container_name: basketdb
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./basketdb/data:/data
        
  catalog_cache:
    container_name: catalog_cache
    restart: always
    ports:
      - "6380:6379"
    volumes:
      - ./catalog_cache/data:/data

  discountdb:
    container_name: discountdb
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=DiscountDb
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
        
  loggingdb:
    container_name: loggingdb
    restart: always
    environment:
      - MYSQL_DATABASE=Logging
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=SwN12345678
    ports:
      - '3306:3306'
    volumes:
      - loggingdb:/var/lib/mysql
      - ./loggingdb/init.sql:/docker-entrypoint-initdb.d/init.sql
      
  orderdb:
    container_name: orderdb
    environment:
      SA_PASSWORD: "SwN12345678"
      ACCEPT_EULA: "Y"
    restart: always
    ports:
      - "1433:1433"
        
  authendb:
    container_name: authendb
    environment:
      SA_PASSWORD: "SwN12345678"
      ACCEPT_EULA: "Y"
    restart: always
    ports:
      - "1434:1433"
  
  rabbitmqdb:
    container_name: rabbitmqdb
    environment:
      SA_PASSWORD: "SwN12345678"
      ACCEPT_EULA: "Y"
    restart: always
    ports:
      - "1435:1433"
        
  workerdb:
    container_name: workerdb
    environment:
      SA_PASSWORD: "SwN12345678"
      ACCEPT_EULA: "Y"
    restart: always
    ports:
      - "1436:1433"
  
  rabbitmq:
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"

  pgadmin:
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@aspnetrun.com
      - PGADMIN_DEFAULT_PASSWORD=admin1234
    restart: always
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/root/.pgadmin

  portainer:
    container_name: portainer
    restart: always
    ports:
      - "8080:8000"
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

  catalog.api:
    container_name: catalog.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:MongoDb:ConnectionString=mongodb://catalogdb:27017"
      - "DatabaseSettings:MongoDb:DatabaseName=ProductDb"
      - "DatabaseSettings:MongoDb:IsRebuildSchema=false"
      - "GrpcSettings:DiscountUrl=http://discount.grpc"
      - ASPNETCORE_URLS=https://+:443
      - ASPNETCORE_Kestrel__Certificates__Default__Password=13Lucifer
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    depends_on:
      - catalogdb
    ports:
      - "8000:443"
    volumes:
      - ~/.aspnet/https:/https:ro

  basket.api:
    container_name: basket.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "JwtSettings:Issuer=http://identityserver"
      - "JwtSettings:Audience=http://ocelotapigw"
      - "JwtSettings:Key=LuciferForTheHellLuciferForTheHellLuciferForTheHellLuciferForTheHell"
      - "JwtSettings:LifeTime=8"
      - "GrpcSettings:DiscountUrl=http://discount.grpc"
      - "CacheSettings:ConnectionString=basketdb:6379"
      - "Microservices:CatalogApi=http://catalog.api"
      - "Microservices:DiscountApi=http://discount.api"
      - "Microservices:OrderingApi=http://ordering.api"
      - "EventBusSettings:HostAddress=amqp://guest:guest@rabbitmq:5672"
      - "EventBusSettings:ConnectionString=Server=rabbitmqdb;Database=Outbox;User Id=sa;Password=SwN12345678;TrustServerCertificate=True;"
      - "EventBusSettings:IsRebuildSchema=false"
    depends_on:
      - catalog.api
      - discount.api
      - ordering.api
      - basketdb
      - rabbitmq
      - rabbitmqdb
    ports:
      - "8001:80"

  discount.api:
    container_name: discount.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:Postgres:ConnectionString=Server=discountdb;Port=5432;Database=DiscountDb;User Id=admin;Password=admin1234;"
      - "DatabaseSettings:Postgres:IsRebuildSchema=false;"
      - "ApiServices:OcelotApiGw=http://ocelotapigw"
    depends_on:
      - discountdb
      - ocelotapigw
    ports:
      - "8002:80"

  discount.grpc:
    container_name: discount.grpc
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:Postgres:ConnectionString=Server=discountdb;Port=5432;Database=DiscountDb;User Id=admin;Password=admin1234;"
      - "DatabaseSettings:Postgres:IsRebuildSchema=false;"
      - ASPNETCORE_Kestrel__Certificates__Default__Password=13Lucifer
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ASPNETCORE_URLS=https://+:443
    depends_on:
      - discountdb
    ports:
#      - "8003:80"
      - "8003:443"
    volumes:
      - ~/.aspnet/https:/https:ro

  ordering.api:
    container_name: ordering.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:OrderingConnectionString=Server=orderdb;Database=OrderDb;User Id=sa;Password=SwN12345678;"
      - "ConnectionStrings:IsRebuildSchema=false"
      - "EventBusSettings:HostAddress=amqp://guest:guest@rabbitmq:5672"
      - "EventBusSettings:ConnectionString=Server=rabbitmqdb;Database=Outbox;User Id=sa;Password=SwN12345678;TrustServerCertificate=True;"
      - "EventBusSettings:IsRebuildSchema=false"
      - "Worker:WorkerConnectionString=Server=workerdb;Database=WorkerDb;User Id=sa;Password=SwN12345678;TrustServerCertificate=True;"
      - "Worker:IsRebuildSchema=false"
    depends_on:
      - orderdb
      - rabbitmq
      - workerdb
      - rabbitmqdb
    ports:
      - "8004:80"

  ocelotapigw:
    container_name: ocelotapigw
    environment:
      - ASPNETCORE_ENVIRONMENT=Local
      - "JwtSettings:Issuer=http://identityserver"
      - "JwtSettings:Audience=http://ocelotapigw"
      - "JwtSettings:Key=LuciferForTheHellLuciferForTheHellLuciferForTheHellLuciferForTheHell"
      - "JwtSettings:LifeTime=8"
    ports:
      - "8010:80"
        
  shopping.aggregator:
    container_name: shopping.aggregator
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ApiSettings:CatalogUrl=http://catalog.api"
      - "ApiSettings:BasketUrl=http://basket.api"
      - "ApiSettings:OrderingUrl=http://ordering.api"
    depends_on:
      - catalog.api
      - basket.api
      - ordering.api
    ports:
      - "8005:80"
        
  identityserver:
    container_name: identityserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "JwtSettings:Issuer=http://identityserver"
      - "JwtSettings:Audience=http://ocelotapigw"
      - "JwtSettings:Key=LuciferForTheHellLuciferForTheHellLuciferForTheHellLuciferForTheHell"
      - "JwtSettings:LifeTime=8"
      - "Configuration:ConnectionString=Server=authendb;Database=AuthenDb;User Id=sa;Password=SwN12345678;"
      - "Configuration:IsRebuildSchema=false"
      - "Configuration:IsSeedData=false"
    depends_on:
      - authendb
      - ocelotapigw
    ports:
      - "8500:80"
        
  jaeger:
    container_name: "jaeger"
    ports:
      - "16686:16686"
  
  prometheus:
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    volumes:
      - ./Configs/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    ports:
      - "9090:9090"
  
  grafana:
    container_name: grafana
    ports:
      - '3000:3000'
    restart: unless-stopped
    volumes:
      - grafana-data:/var/lib/grafana
  
  otel-collector:
    container_name: otel-collector
    command: [ "--config=/etc/otel-collector-config.yml" ]
    volumes:
      - ./Configs/otel-collector-config.yml:/etc/otel-collector-config.yml
    ports:
      - "1888:1888"   # pprof extension
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "4317:4317"   # OTLP gRPC receiver
      - "4318:4318"   # Http gRPC receiver
      - "55679:55679" # zpages extension
      - "14250:14250"   # Jaeger receiver
        
  elasticsearch:
    container_name: elasticsearch
    ports:
      - "5601:5601"
      - "9200:9200"
      - "5044:5044"
      - "9300:9300"    
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data